# Simple configuration for HealthTRAC prototype

fsr:
  port: null  # Auto-detect
  baudrate: 115200

metamotion:
  mac_address: null  # Auto-detect

dashboard:
  refresh_rate: 20  # Hz
  window_seconds: 10  # Show last N seconds